import type { Metadata } from "next";
import MainLayout from "@/layouts/MainLayout";

export const metadata: Metadata = {
  title: "zora defence",
  description: "Generated by Milologic",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <MainLayout>{children}</MainLayout>;
}