import type { Metadata } from "next";
import "./globals.css";
import {Lora} from "next/font/google"
import MainLayout from "@/layouts/MainLayout";

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={lora.className}
      >
       {children}
      </body>
    </html>
  );
}
